name: sticky disk BuildKit example

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: tenki-standard-medium-4c-8g
    steps:
      - uses: actions/checkout@v6
      - id: buildkit
        uses: LuxorLabs/stickydisk/buildkit@v1
        with:
          key: buildkit-${{ runner.arch }}
          path: /var/lib/buildkit
      - uses: docker/build-push-action@v7
        with:
          builder: ${{ steps.buildkit.outputs.name }}
          context: .
          push: false
